/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#ff5a00",
        "primary-dim": "#d94800",
        "primary-container": "#fff0e7",
        "on-primary": "#000000",
        "on-primary-container": "#2a1200",
        surface: "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f1",
        "surface-container": "#e8e8e2",
        "surface-container-high": "#d6d6ce",
        "surface-variant": "#c6c6bd",
        "on-surface": "#050505",
        "on-surface-variant": "#4a4a44",
        outline: "#111111",
        "outline-variant": "#b9b9af",
        secondary: "#0a7f3c",
        "secondary-container": "#e7f6ed",
        "on-secondary-container": "#052c17",
        warning: "#b85f00",
        error: "#b00020",
      },
      borderRadius: {
        DEFAULT: "0",
        lg: "0",
        xl: "0",
        "2xl": "0",
        "3xl": "0",
        full: "9999px",
      },
      fontFamily: {
        sans: ["IBM Plex Sans Condensed", "sans-serif"],
        headline: ["IBM Plex Sans Condensed", "sans-serif"],
        body: ["IBM Plex Sans Condensed", "sans-serif"],
        label: ["IBM Plex Sans Condensed", "sans-serif"],
        mono: ["IBM Plex Mono", "monospace"],
      },
    },
  },
  plugins: [],
};
